### ISSUE TITLE
Compatability with Tomcat and Mule ESB?

### ISSUE THREAD

**Issue by DavidHaasz** [fstab/promagent#2]
This looks like a great library to use for white box monitoring! Just wondered if its compatible with Tomcat and Mule ESB?

**Comment by fstab** [comment]
Hi David, I would not call it a library, because you cannot use it as it is. It's more an example code. In order to use it, you have to clone it and replace the Hooks and Metrics with something that's useful for your scenario.
Tomcat works, this is what the Spring Boot demo uses (if you have Docker, call `mvn clean verify -Pspring` to run an integration test against a Docker container). I did not tested it with the Mule ESB, but if you try it I would be very interested in the result :)
